networks:
  library-network:
    driver: bridge
services:
  postgres:
    image: postgres:16.6
    container_name: libraryDB
    ports:
      - "5440:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=library
    networks:
      - library-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - "15432:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - postgres
    networks:
      - library-network
