spring:
  datasource:
    url: jdbc:postgresql://localhost:5440/library
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true